version: "3.7"
networks:
  app-tier:
services:
  db:
    image: postgres:12
    restart: always
    networks:
      - app-tier
    environment:
      POSTGRES_USER: todos
      POSTGRES_PASSWORD: 123456
    ports:
      - 25432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    networks:
      - app-tier
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.dev
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - 8080:80